apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 8329557283/node
        ports:
        - containerPort: 3000 

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
